name: Release new versions

env:
  VITE_VERCEL_ENV: production

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v7.0.1

      - run: |
          echo "Before: corepack version => $(corepack --version || echo 'not installed')"
          npm install -g corepack@latest
          echo "After : corepack version => $(corepack --version)"
          corepack enable
          pnpm --version

      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --ignore-scripts

      - name: Build the app
        run: pnpm build

      - name: Zip the app
        run: zip -r dev-tools-${{ env.RELEASE_VERSION }}.zip dist/*

      - name: Get changelog
        id: changelog
        run: |
          EOF=$(openssl rand -hex 8)
          echo "changelog<<$EOF" >> $GITHUB_OUTPUT
          node ./scripts/getLatestChangelog.mjs >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v3.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dev-tools-${{ env.RELEASE_VERSION }}.zip
          tag_name: v${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
          make_latest: "true"
          body: |
            Release ${{ env.RELEASE_VERSION }}

            ## Changelog

            ${{ steps.changelog.outputs.changelog }}
